#!/bin/sh

BASEDIR=`pwd`
cd $BASEDIR
BASEDIR=`pwd`

cp $BASEDIR/misc/backspring $BASEDIR/bin/backspring

sed -i "s|DAEMON=/usr/sbin/backspring|DAEMON=$BASEDIR/bin/backspring-main|" $BASEDIR/bin/backspring  

cp $BASEDIR/bin/backspring /etc/init.d/backspring

rm -f /etc/rc5.d/S99backspring

ln -s ../init.d/backspring /etc/rc5.d/S99backspring